services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/certbot/conf:/etc/letsencrypt
    depends_on:
      - client
      - server
    networks:
      - camagru_net
  client:
    build: ./client
    container_name: client
    networks:
      - camagru_net
  
  server:
    build: ./server
    container_name: server
    env_file:
      - ./shared/.env 
    networks:
      - camagru_net
    volumes:
      - ./server/model/data:/var/www/html/model

networks:
  camagru_net:
    external: true
    name: camagru_net

volumes:
  server_data:
    driver: local
    driver_opts:
      type: none
      device: ./server
      o: bind
